### ISSUE TITLE
Image missing in Artshow on Chrome 

### ISSUE THREAD

**Issue by peterpol01** [scripting/artDownloader#1]
When attempting to use Artshow in latest Google Chrome browser (V. 90.0.4430.93), a blank tab opens with the text description below where I assume the image to be.  Right clicking in the image area and selecting "open image in new tab" performs as expected with image displayed in new tab. Attached below is screen shot with errors from console:
![Artshow errors 05_07_21](https://user-images.githubusercontent.com/69479662/117482946-1aa2c580-af33-11eb-9b2b-a6b62d4a94c2.JPG)

**Comment by scripting** [comment]
Peter thanks for the report. My guess is that you have an extension of some kind running, the problem appears to be in the extension not in Art Show.

**Comment by peterpol01** [comment]
You are correct! I opened chrome in safe mode and it worked.  Just need to figure which extension is causing the problem. Or, more likely, just run in it in a safe mode window!

**Comment by scripting** [comment]
>>You are correct!

Bronx Science.
